"""empty message

Revision ID: 4ca9421721d3
Revises: ec43d6457915
Create Date: 2020-12-06 12:41:28.121155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca9421721d3'
down_revision = 'ec43d6457915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('fighter_1_odds', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('fighter_2_odds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'fighter_2_odds')
    op.drop_column('events', 'fighter_1_odds')
    # ### end Alembic commands ###
