"""empty message

Revision ID: ec43d6457915
Revises: a01ce2d88aff
Create Date: 2020-12-04 19:02:12.993819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec43d6457915'
down_revision = 'a01ce2d88aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('fight_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'fight_order')
    # ### end Alembic commands ###
