"""empty message

Revision ID: f23e9899c570
Revises: 
Create Date: 2020-12-06 20:18:20.268420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23e9899c570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('fighter_1', sa.String(), nullable=True),
    sa.Column('fighter_2', sa.String(), nullable=True),
    sa.Column('fighter_1_votes', sa.Integer(), nullable=True),
    sa.Column('fighter_2_votes', sa.Integer(), nullable=True),
    sa.Column('fighter_1_odds', sa.Integer(), nullable=True),
    sa.Column('fighter_2_odds', sa.Integer(), nullable=True),
    sa.Column('fight_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('arm_reach', sa.Float(), nullable=True),
    sa.Column('leg_reach', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fighters')
    op.drop_table('events')
    op.drop_table('divisions')
    # ### end Alembic commands ###
